// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktntnhliuvngqyaiqgqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0bnRuaGxpdXZuZ3F5YWlxZ3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTczOTUsImV4cCI6MjA3NDA5MzM5NX0.Z0dm_eN2cvOtIXZB0sQBlPZci3Em6E1vB0mVkjQMOP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});